# Generated by Django 2.2.24 on 2025-02-09 15:24

from django.db import migrations

from phonenumbers import parse, is_valid_number, format_number, PhoneNumberFormat

def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_phone = parse(flat.owners_phonenumber, 'RU')
                if is_valid_number(parsed_phone):
                    flat.owner_pure_phone = format_number(parsed_phone, PhoneNumberFormat.E164)
                    flat.save()
            except Exception as e:
                print(f"Ошибка при обработке телефона {flat.owners_phonenumber}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
