# Generated by Django 2.2.24 on 2025-02-16 08:50

from django.db import migrations


def transfer_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250216_1142'),
    ]

    operations = [
        migrations.RunPython(transfer_flats_to_owners),
    ]
