# Generated by Django 2.2.24 on 2025-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250219_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners_of_flats', to='property.Flat', verbose_name='Квартиры'),
        ),
    ]
