# Generated by Django 2.2.24 on 2025-02-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20250219_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.Flat', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Наличие балкона'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_number',
            field=models.IntegerField(db_index=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town_district',
            field=models.CharField(blank=True, help_text='Чертаново Южное', max_length=50, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners_set', to='property.Flat', verbose_name='Квартиры'),
        ),
    ]
